." Process this file with
." groff -man -Tascii pdfgui_tools.1
."
.TH pdfgui_tools "1" "" "" "User commands"

.SH NAME
pdfgui_tools - PDF GUI Tools

.SH SYNOPSIS
.B pdfgui_tools
.OP OPTIONS

.SH DESCRIPTION
.B pdfgui_tools
is a GUI tool that includes the poppler-utils and PyPDF2 tools for working with PDF documents. It includes the following utilities:

.RS
.nf
- Merge PDFs:					its purpose is to merge multiple PDFs into a single one.
- Encrypt PDFs					its for encrypting PDF documents.
- Decrypt PDFs					its for decrypting PDF documents.
- Separate PDF					its purpose is to split PDF documents.
- Convert PDF					its for converting the PDF to the selected format.
.RE

.SH OPTIONS

.B "-h | --help"\fR
		Prints help.

.B "-m | --man"\fR
		 Man page.

.B "-v | --version"\fR
	  Prints version.

.SH AUTHOR 
.PP
Developed by Angel Gabriel Mortera Gual <https://github.com/TheWatcherMultiversal>


.SH REPORTING BUGS
.PP
Report errors or suggestions to my email <universepenguin@protonmail.com>

.SH SEE ALSO
.PP
.br
More information in <https://github.com/TheWatcherMultiversal/pdfgui_tools>

