#!/bin/bash

# pdfgui_tools: startup script
# License: GNU General Public License v3.0
# Developed by: Angel Gabriel Mortera Gual
# Github project: https://github.com/TheWatcherMultiversal/pdfgui_tools

# Options

set -e

PDFGUI_TOOLS_VERSION="v1.1.0"

case "$1" in
-h|--help)
    echo $"
Usage: pdfgui_tools [OPTIONS]
  -h  --help              print this help and exit
  -m, --man               man page
  -v, --version           print version
"
        ;; 
-m|--man)
        man pdfgui_tools
        ;;
-v|--version)
        echo "$PDFGUI_TOOLS_VERSION"
        ;;
*)
        python3 /usr/share/pdfgui_tools/pdfgui_tools.py
esac
