# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdfgui_tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(381, 339)
        MainWindow.setMinimumSize(QtCore.QSize(381, 339))
        MainWindow.setMaximumSize(QtCore.QSize(381, 362))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 70, 251, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pdfunite_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pdfunite_button.setObjectName("pdfunite_button")
        self.verticalLayout.addWidget(self.pdfunite_button)
        self.pdfseparate_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pdfseparate_button.setObjectName("pdfseparate_button")
        self.verticalLayout.addWidget(self.pdfseparate_button)
        self.pdftocairo_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pdftocairo_button.setObjectName("pdftocairo_button")
        self.verticalLayout.addWidget(self.pdftocairo_button)
        self.pdftohtml_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pdftohtml_button.setObjectName("pdftohtml_button")
        self.verticalLayout.addWidget(self.pdftohtml_button)
        self.pdftotext_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pdftotext_button.setObjectName("pdftotext_button")
        self.verticalLayout.addWidget(self.pdftotext_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 24))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF GUI Tools"))
        self.label.setText(_translate("MainWindow", "PDF gui Tools"))
        self.pdfunite_button.setText(_translate("MainWindow", "Merge PDFs"))
        self.pdfseparate_button.setText(_translate("MainWindow", "Separate PDF"))
        self.pdftocairo_button.setText(_translate("MainWindow", "PDF to multimedia file"))
        self.pdftohtml_button.setText(_translate("MainWindow", "PDF to html"))
        self.pdftotext_button.setText(_translate("MainWindow", "PDF to text"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
